In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [7]:
data = pd.read_csv("password-data.csv",on_bad_lines='skip')

In [8]:
data.head()

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [9]:
data.isnull().sum()

password    1
strength    0
dtype: int64

In [11]:
data = data.dropna()

In [12]:
data['strength'] = data['strength'].map({0:'Weak',1:'Medium',2:'Strong'})

In [13]:
data.head()

password strength
0     kzde5577   Medium
1     kino3434   Medium
2    visi7k1yr   Medium
3     megzy123   Medium
4  lamborghin1   Medium

In [14]:
def word(password):
    character=[]
    for i in password:
        character.append(i)
    return character
  
x = np.array(data["password"])
y = np.array(data["strength"])

tdif = TfidfVectorizer(tokenizer=word)
x = tdif.fit_transform(x)

D:\Anaconda\envs\ML-Env\Lib\site-packages\sklearn\feature_extraction\text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [15]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.05, random_state=42)

In [16]:
model = RandomForestClassifier()
model.fit(xtrain, ytrain)
print(model.score(xtest, ytest))


KeyboardInterrupt



In [ ]:
import getpass
user = getpass.getpass("Enter Password: ")
data = tdif.transform([user]).toarray()
output = model.predict(data)
print(output)

In [17]:
# Count Vectorizer

In [19]:


# Example documents
documents = [
    "Machine learning is fascinating.",
    "I love learning about AI.",
    "Machine learning and AI are related fields."
]

# Initialize CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the documents
X = vectorizer.fit_transform(documents)

# Get the feature names (i.e., the words in the vocabulary)
feature_names = vectorizer.get_feature_names_out()

# Convert the sparse matrix to a dense array for better readability
X_dense = X.toarray()

# Display the results
print("X:",X)
print("Vocabulary:", feature_names)
print("Document-Term Matrix:\n", X_dense)

X: <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 15 stored elements and shape (3, 11)>
  Coords	Values
  (0, 9)	1
  (0, 7)	1
  (0, 6)	1
  (0, 4)	1
  (1, 7)	1
  (1, 8)	1
  (1, 0)	1
  (1, 1)	1
  (2, 9)	1
  (2, 7)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	1
  (2, 10)	1
  (2, 5)	1
Vocabulary: ['about' 'ai' 'and' 'are' 'fascinating' 'fields' 'is' 'learning' 'love'
 'machine' 'related']
Document-Term Matrix:
 [[0 0 0 0 1 0 1 1 0 1 0]
 [1 1 0 0 0 0 0 1 1 0 0]
 [0 1 1 1 0 1 0 1 0 1 1]]
